<?php

/**
 * @file
 * User loan listing and renewal functionallity.
 */

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * ctools_plugin_example/panels are used.
 */
function ding_loan_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_ding_provider_user().
 */
function ding_loan_ding_provider_user() {
  return array(
    'loan' => array(
      'required' => TRUE,
      'install time setup' => TRUE,
    ),
  );
}

/**
 * Callback function for sorting loans.
 */
function ding_loan_sort_expiry($a, $b) {
  if ($a->expiry == $b->expiry) {
    return 0;
  }
  return ($a->expiry < $b->expiry) ? -1 : 1;
}

/**
 * Draw table with loan items.
 *
 * Same as 'ding_provider_get_form' but without form.
 *
 * @param array $form_builder
 *   Form ID.
 * @param array $loans
 *   Array with load info.
 *
 * @return array
 *   Render array.
 */
function ding_loan_get_table($form_builder, $loans) {
  // Fake form creation.
  $form = array();
  $form_state = array();
  $table = $form_builder($form, $form_state, NULL, $loans);

  // Remove empty cell before 'title'.
  $rows = $table['loans']['table']['#options'];
  foreach ($rows as $key => $row) {
    unset($row['#disabled']);
    $rows[$key] = $row;
  }

  $output = array(
    '#theme' => 'table',
    '#header' => $table['loans']['table']['#header'],
    '#empty' => $table['loans']['table']['#empty'],
    '#rows' => $rows,
  );

  // Return only markup.
  return $output;
}
